# Generated by Django 4.0.5 on 2022-07-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('in_process', 'in_process'), ('canceled', 'canceled'), ('delivered', 'delivered')], default='open', max_length=50),
        ),
    ]
